In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [6]:
url = "https://www.worldometers.info/world-population/population-by-country/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [7]:
soup = BeautifulSoup(response.text, "html.parser")

In [8]:
table = soup.find("table")

print(table)

<table class="datatable w-full border border-zinc-200" data-locale="en" data-options='{"searchable":true,"sortable":true,"defaultSort":"#","pageSize":false}' data-sort-col="0" data-sort-dir="asc" id=""> <thead> <tr> <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>#</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>Country (or dependency)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Population 2026</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Yearly Change</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Net Change</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Density (P/KmÂ²)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Land Area (KmÂ²)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Migrants (net)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Fert. Rate</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Median Age</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Urban Pop %</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>World Share</span> </th> </tr> </thead> <tbody> <tr id="india"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 1 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14766255760000" dir="ltr"> 1,476,625,576 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87" dir="ltr"> 0.87% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="127600510000" dir="ltr"> 12,760,051 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4966469" dir="ltr"> 497 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="29731900000" dir="ltr"> 2,973,190 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-4404560000" dir="ltr"> â440,456 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19290" dir="ltr"> 1.93 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292160" dir="ltr"> 29.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3761" dir="ltr"> 37.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1779" dir="ltr"> 17.79% </td> </tr><tr id="china"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14129140890000" dir="ltr"> 1,412,914,089 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-22" dir="ltr"> â0.22% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-31820050000" dir="ltr"> â3,182,005 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1504988" dir="ltr"> 150 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="93882110000" dir="ltr"> 9,388,211 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2321070000" dir="ltr"> â232,107 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10310" dir="ltr"> 1.03 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406480" dir="ltr"> 40.6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6868" dir="ltr"> 68.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1702" dir="ltr"> 17.02% </td> </tr><tr id="us"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="3490354940000" dir="ltr"> 349,035,494 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="51" dir="ltr"> 0.51% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17596870000" dir="ltr"> 1,759,687 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="381567" dir="ltr"> 38 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="91474200000" dir="ltr"> 9,147,420 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="11778480000" dir="ltr"> 1,177,848 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="16250" dir="ltr"> 1.63 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="387130" dir="ltr"> 38.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8313" dir="ltr"> 83.1% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="420" dir="ltr"> 4.20% </td> </tr><tr id="indonesia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 4 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2878867820000" dir="ltr"> 287,886,782 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="76" dir="ltr"> 0.76% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21655460000" dir="ltr"> 2,165,546 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1589156" dir="ltr"> 159 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18115700000" dir="ltr"> 1,811,570 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-394720000" dir="ltr"> â39,472 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20800" dir="ltr"> 2.08 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="306590" dir="ltr"> 30.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6027" dir="ltr"> 60.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="347" dir="ltr"> 3.47% </td> </tr><tr id="pakistan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 5 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2592997910000" dir="ltr"> 259,299,791 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="40802370000" dir="ltr"> 4,080,237 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3363686" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7708800000" dir="ltr"> 770,880 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-11447380000" dir="ltr"> â1,144,738 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34420" dir="ltr"> 3.44 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="207710" dir="ltr"> 20.8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3470" dir="ltr"> 34.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="312" dir="ltr"> 3.12% </td> </tr><tr id="nigeria"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2424318320000" dir="ltr"> 242,431,832 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="206" dir="ltr"> 2.06% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="49040500000" dir="ltr"> 4,904,050 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2661834" dir="ltr"> 266 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9107700000" dir="ltr"> 910,770 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-28100000" dir="ltr"> â2,810 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="42050" dir="ltr"> 4.21 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="183480" dir="ltr"> 18.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="5580" dir="ltr"> 55.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292" dir="ltr"> 2.92% </td> </tr><tr id="brazil"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2135626660000" dir="ltr"> 213,562,666 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="35" dir="ltr"> 0.35% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7502610000" dir="ltr"> 750,261 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="255515" dir="ltr"> 26 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="83581400000" dir="ltr"> 8,358,140 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2056420000" dir="ltr"> â205,642 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="15910" dir="ltr"> 1.59 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="352500" dir="ltr"> 35.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9174" dir="ltr"> 91.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="257" dir="ltr"> 2.57% </td> </tr><tr id="bangladesh"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1778180440000" dir="ltr"> 177,818,044 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="121" dir="ltr"> 1.21% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21311450000" dir="ltr"> 2,131,145 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="13660447" dir="ltr"> 1,366 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1301700000" dir="ltr"> 130,170 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-3713980000" dir="ltr"> â371,398 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20900" dir="ltr"> 2.09 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="263020" dir="ltr"> 26.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4321" dir="ltr"> 43.2% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="214" dir="ltr"> 2.14% </td> </tr><tr id="russia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1433944580000" dir="ltr"> 143,394,458 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-42" dir="ltr"> â0.42% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6029350000" dir="ltr"> â602,935 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87559" dir="ltr"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="163768700000" dir="ltr"> 16,376,870 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3249240000" dir="ltr"> 324,924 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="14700" dir="ltr"> 1.47 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406950" dir="ltr"> 40.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7541" dir="ltr"> 75.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="173" dir="ltr"> 1.73% </td> </tr><tr id="ethiopia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 10 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/ethiopia-population/"> Ethiopia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1389021850000" dir="ltr"> 138,902,185 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="253" dir="ltr"> 2.53% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34301340000" dir="ltr"> 3,430,134 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1389022" dir="ltr"> 139 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10000000000" dir="ltr"> 1,000,000 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="272980000" dir="ltr"> 27,298 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="37230" dir="ltr"> 3.72 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="193410" dir="ltr"> 19.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2290" dir="ltr"> 22.9% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="167" dir="ltr"> 1.67% </td> </tr><tr id="mexico"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 11 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/mexico-population/"> Mexico </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1329976580000" dir="ltr"> 132,997,658 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="80" dir="ltr"> 0.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10507580000" dir="ltr"> 1,050,758 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="684162" dir="ltr"> 68 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19439500000" dir="ltr"> 1,943,950 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-1098440000" dir="ltr"> â109,844 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18520" dir="ltr"> 1.85 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="299950" dir="ltr"> 30 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8830" dir="ltr"> 88.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.60% </td> </tr><tr id="japan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 12 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/japan-population/"> Japan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1224277310000" dir="ltr"> 122,427,731 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-55" dir="ltr"> â0.55% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6757480000" dir="ltr"> â675,748 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3358279" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3645550000" dir="ltr"> 364,555 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1286190000" dir="ltr"> 128,619 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="12310" dir="ltr"> 1.23 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="501810" dir="ltr"> 50.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9335" dir="ltr"> 93.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.47% </td> </tr><tr id="egypt"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 13 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/8

In [9]:
rows = table.find_all("tr")

In [12]:
header_row = table.find("tr")

headers = [th.text.strip() for th in header_row.find_all("th")]
print(headers)

['#', 'Country (or dependency)', 'Population 2026', 'Yearly Change', 'Net Change', 'Density (P/KmÂ²)', 'Land Area (KmÂ²)', 'Migrants (net)', 'Fert. Rate', 'Median Age', 'Urban Pop %', 'World Share']

In [10]:
data = []

for row in rows[1:]:
    cols = row.find_all("td")
    
    if len(cols) > 0:
        data.append([col.text.strip() for col in cols])

In [13]:
df = pd.DataFrame(data, columns=headers)

df.head()

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","â440,456",1.93,29.2,37.6%,17.79%
1,2,China,"1,412,914,089",â0.22%,"â3,182,005",150,"9,388,211","â232,107",1.03,40.6,68.7%,17.02%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.20%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","â39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","â1,144,738",3.44,20.8,34.7%,3.12%

In [14]:
print(df.shape)
print(df.columns)
df.head()

(234, 12)
Index(['#', 'Country (or dependency)', 'Population 2026', 'Yearly Change',
       'Net Change', 'Density (P/KmÂ²)', 'Land Area (KmÂ²)', 'Migrants (net)',
       'Fert. Rate', 'Median Age', 'Urban Pop %', 'World Share'],
      dtype='object')

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","â440,456",1.93,29.2,37.6%,17.79%
1,2,China,"1,412,914,089",â0.22%,"â3,182,005",150,"9,388,211","â232,107",1.03,40.6,68.7%,17.02%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.20%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","â39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","â1,144,738",3.44,20.8,34.7%,3.12%

In [15]:
df = df.replace(",", "", regex=True)

In [16]:
df.to_csv("world_population.csv", index=False)